### PR TITLE
Updated definition of attendance in FAQ Fixes #1156

### LINKED ISSUE #1156: Explanation of what "attendence figures mean" is very unclear
See https://theyvoteforyou.org.au/help/faq#attendance

It currently says:

> ## What do the "attendance" figures mean?
> 
> "Attendance" figures record the politicians who vote in any given division.

I don't think I would understand what's intended if I read this. This should be in simple plain English. It currently doesn't meet our [design principles](https://github.com/openaustralia/publicwhip/blob/master/design_docs/principles.md) or match the [project’s voice](https://github.com/openaustralia/publicwhip/blob/master/design_docs/design_persona.md#voice).

### PR DESCRIPTION
**Pull request by Taz17**
Updated definition of attendance in FAQ.

Using the definition published on aph.gov.au [here](https://www.aph.gov.au/About_Parliament/House_of_Representatives/Powers_practice_and_procedure/Practice7/HTML/Chapter5/Attendance)

I removed both URL's in the previous version of the definition as both links led to a 404/content not found

I also kept part of the old definition which explains the reasons why a member could have low attendance

### CODE REVIEW

**Comment by bobsbarrels** [comment]
Heya @Taz17 just realised we have conflicting PRs, where I was working on #1289 

I fixed the broken URLs in conversation with @katska ... see: https://github.com/openaustralia/publicwhip/pull/1296

It's nice PEO website has upgraded to `https` just they don't have `#id`s for linking and their website wasn't totally stable for me.

**Comment by Taz17** [comment]
Thats ok, this PR addresses issue #1156.

Its about simplifying the definition of attendance.

Once any of the two PR's get accepted we can work out what will be included/excluded from the definition.

@katska would love your contribution to this issue as well as #1296 as mentioned by @bobsbarrels

**Review by mlandauer — COMMENTED** [review]
I've given some specific feedback on the different parts of the wording change that you've suggested. I don't know if it's worth starting from scratch or trying to update based on the feedback.

What we tend to do with wording changes is flesh them out in a shared google doc between ourselves (super important to get @katska involved in this). It can be really hard working through wording changes (unless they're really small) in a PR. It just gets unwieldy fast! :-(

**Comment by Taz17** [comment]
Closing since definitions have been fixed in an earlier PR.

**Pull request closed without merging**
