### PR TITLE
Screenshot rake task

### PR DESCRIPTION
**Pull request by Taz17**
Could now automatically take screenshots of all social media sharing cards. As described in https://github.com/openaustralia/publicwhip/issues/1338.

Once #1340 is done we can add `task("application:generate:cards").invoke` to the daily rake task

### CODE REVIEW

**Comment by Taz17** [comment]
CI build failed because of a segmentation fault. Something with `sassc`

https://app.travis-ci.com/github/openaustralia/publicwhip/jobs/560643935#L821

**Comment by mlandauer** [comment]
I've restarted the job on travis 🤞🏼

**Comment by Taz17** [comment]
Another segmentation fault :|

**Comment by Taz17** [comment]
On this github issue https://github.com/sass/sassc-ruby/issues/197 it discusses the same problem with a previous version of sassc (2.3.0) another person using 2.4.0 had the same error https://github.com/sass/sassc-ruby/issues/197#issuecomment-648889921.

A solution that worked for some is adding this snippet to `config/initializers/assets.rb`
```
Rails.application.config.assets.configure do |env|
  env.export_concurrent = false
end
```

**Comment by Taz17** [comment]
@mlandauer could you take a look at this PR now. I'd like to know if there are any knock on affects after setting `export_concurrent = false`.

**Comment by mlandauer** [comment]
> @mlandauer could you take a look at this PR now. I'd like to know if there are any knock on affects after setting `export_concurrent = false`.

Please make a separate pull request for the `export_concurrent` change. Then we can check on its own whether it can be safely rolled out to production. Similar to the other pull request I'm going to close this one and wait until you open a new pull request with a cleaned up version history.

**Pull request closed without merging**
