### PR TITLE
Added length validation for Policy name

### LINKED ISSUE #1101: They Vote For You raises an error if you enter a policy title that's "too long" instead of giving you helpful feedback
[They Vote For You/production] Mysql2::Error: Data too long for column 'name' at row 1
## Backtrace

```
line 50 of [PROJECT_ROOT]/app/controllers/policies_controller.rb: create
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37542/faults/30697246)

### PR DESCRIPTION
**Pull request by mario-areias**
Fixes #1101 

I do not have much experience with Ruby on Rails, so I am not sure what's the best practice when testing active record. Let me know if something is wrong with it.

### CODE REVIEW

**Comment by equivalentideas** [comment]
@mario-areias really nice 👌 this is basically exactly how we like tests. The description could be clearer, and I like spaces between the test phases, but aside from that, very nice :)

The other thing is, the current database column constraint is 100 characters, rather than 50. If we put a 50 character constraint on, it would mean that quick a few of our existing policies would be invalid :) ["For imprisoning immigration detention workers who record or reveal information from their work "](https://theyvoteforyou.org.au/policies/119), ["For compensating victims of overseas terrorism since the September 11 attack"](https://theyvoteforyou.org.au/policies/65), and ["
For greater public scrutiny of the Trans-Pacific Partnership negotiations "](https://theyvoteforyou.org.au/policies/73).

**Comment by equivalentideas** [comment]
I'll make those changes on top of this so you can see our approach :)

**Comment by mario-areias** [comment]
Ha, great. I don't know where I got that number from, sorry about that.

**Comment by equivalentideas** [comment]
@mario-areias Thanks for this contribution ❤️ I've made those changes and merged :) You can see what I did here https://github.com/openaustralia/publicwhip/compare/86194e7bc603...e28bb0650c85 and checkout the individual commit messages for more info.

Nice work with the tests, pretty darn spot on for someone without much experience with rails. Here's one guide that we find useful http://betterspecs.org/

**Comment by mario-areias** [comment]
Thanks for the link. I will read it and make a better PR next time :)

**Comment by equivalentideas** [comment]
> Thanks for the link. I will read it and make a better PR next time :)

Thanks for diving in @mario-areias :)

**Pull request merged**
