### PR TITLE
Rails 4 2 7

### LINKED ISSUE #1104: Rails 4.1 is no longer supported
http://weblog.rubyonrails.org/2016/7/13/Rails-4-2-7-and-4-1-16-have-been-released/

We need to [upgrade to Rails 4.2](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2).

### PR DESCRIPTION
**Pull request by equivalentideas**
This upgrades the version of rails publicwhip runs on to 4.2.7. [4.1 is no longer supported](https://github.com/openaustralia/publicwhip/issues/1104).

You can see on issue https://github.com/openaustralia/publicwhip/issues/1104 how I've worked through the test failures and depreciation warnings. I've upgraded a few gems that were causing deprecation warnings or had bug fixes relating to this upgrade.

I've also tested our clicking through the site, making changes and receiving emails.

It's Friday night, so I'm not gonna push such a big change onto master till next week.

Fixes #1104

### CODE REVIEW

**Comment by henare** [comment]
Parliament's just returned so we decided to hold of deploying this until next week (beginning September 5). I'll assign @equivalentideas to remember to follow this up.

**Comment by henare** [comment]
Great work BTW! :smiley:

**Comment by equivalentideas** [comment]
> Great work BTW! 😃

💟 

> Parliament's just returned so we decided to hold of deploying this until next week (beginning September 5). I'll assign @equivalentideas to remember to follow this up.

👍  I've set slackbot to remind me.

**Comment by henare** [comment]
>:+1: I've set slackbot to remind me.

I guess Slackbot got slack. Since today is the last day we'll import votes for a while I think it's important to get this merged and deployed. Assigning to me.

**Pull request merged**
